In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np

In [6]:
urban

,area,id,revenue_ci,district_3,object_id,district_1,revenue_cr,longitude,latitude,geometry
0,2.320,1,Mankachar,SOUTH SALMARA MANCACHAR,257,South Salmara Mancachar,Mankachar,89.863913,25.528749,"POLYGON ((89.85708 25.52458, 89.85708 25.53292..."
1,85.747,2,Mankachar,SOUTH SALMARA MANCACHAR,257,South Salmara Mancachar,Mankachar,89.888590,25.698188,"POLYGON ((89.88208 25.64125, 89.88208 25.64958..."
2,0.773,3,Mankachar,SOUTH SALMARA MANCACHAR,257,South Salmara Mancachar,Mankachar,89.928627,25.646718,"POLYGON ((89.92375 25.64125, 89.92375 25.64958..."
3,6.931,4,Dhubri (Pt),DHUBRI,112,Dhubri,Dhubri (Pt),89.979711,26.029384,"POLYGON ((89.96542 26.03292, 89.97375 26.03292..."
4,4.618,5,Dhubri (Pt),DHUBRI,112,Dhubri,Dhubri (Pt),89.980141,26.092077,"POLYGON ((89.98208 26.09125, 89.97375 26.09125..."
...,...,...,...,...,...,...,...,...,...,...
176,5.318,177,Doom Dooma,TINSUKIA,155,Tinsukia,Doom Dooma,95.567652,27.598153,"POLYGON ((95.55708 27.60792, 95.56542 27.60792..."
177,0.760,178,Doom Dooma,TINSUKIA,155,Tinsukia,Doom Dooma,95.659610,27.628244,"POLYGON ((95.66542 27.62458, 95.65708 27.62458..."
178,0.759,179,Doom Dooma,TINSUKIA,155,Tinsukia,Doom Dooma,95.558260,27.674442,"POLYGON ((95.55708 27.66625, 95.55708 27.67458..."
179,0.759,180,Doom Dooma,TINSUKIA,155,Tinsukia,Doom Dooma,95.592361,27.754740,"POLYGON ((95.59042 27.74958, 95.59042 27.75792..."
180,2.274,181,Jonai,DHEMAJI,152,Dhemaji,Jonai,95.226359,27.831965,"POLYGON ((95.22375 27.81625, 95.22375 27.82458..."

In [26]:
urban = gpd.read_file(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\IDS-DRR-Assam\Sources\ANTYODAYA\data\assam_urban_shapes\assam_urban_pd_grt_2000.shp')
rc_updated = gpd.read_file(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\IDS-DRR-Assam\Maps\as_ids-drr_shapefiles\assam_rc_2024-11.geojson')
rc_updated['object_id_old'] = rc_updated['object_id'].str[9:12].astype(int)
merged = pd.merge(urban,rc_updated[['object_id','object_id_old']],left_on="object_id",right_on="object_id_old", how="left")
merged = merged.drop(['object_id_x','object_id_old'],axis=1)
merged = merged.rename(columns={'object_id_y':'object_id'})

In [27]:
merged.to_file(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\IDS-DRR-Assam\Sources\ANTYODAYA\data\assam_urban_shapes\assam_urban_objectid_update.geojson')